# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tensr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tensr
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'

  target 'tensrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tensrUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
